/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By using an array, we tell Docusaurus to create a single sidebar.
  // The 'autogenerated' type finds all docs in the dirName and creates a sidebar.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
